name: XiaomiHelper CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README**.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Get short SHA
      run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Decode android signing key
      run: echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks

    - name: Build apks
      run: ./gradlew assembleDebug && ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: "../keystore.jks"
        KEYSTORE_PWD: ${{ secrets.KEYSTORE_PWD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PWD: ${{ secrets.KEY_PWD }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: XiaomiHelper-arm64-v8a-${{ env.SHA7 }}
        path: app/build/outputs/apk/release
      
    - name: Post to Telegram ci channel
      if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.ref_type != 'tag' }}
      env:
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: |+
          New CI from HowieHChen/XiaomiHelper

          ```
          ${{ github.event.head_commit.message }}
          ```
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export RELEASE=$(find ./app/build/outputs/apk/release -name "*.apk")
          export DEBUG=$(find ./app/build/outputs/apk/debug -name "*.apk")
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$RELEASE" -F debug="@$DEBUG"
        fi
